/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Tue Feb 06 08:35:04 2018. */

#include "sensorbug.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SensorMessage_fields[17] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, SensorMessage, count_in, count_in, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, SensorMessage, count_out, count_in, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, SensorMessage, batteryVoltage, count_out, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, SensorMessage, batteryLevel, batteryVoltage, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, SensorMessage, pir_status, batteryLevel, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, SensorMessage, light, pir_status, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, SensorMessage, mic, light, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, SensorMessage, accelx, mic, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC  , OTHER, SensorMessage, accely, accelx, 0),
    PB_FIELD( 10, FLOAT   , REQUIRED, STATIC  , OTHER, SensorMessage, accelz, accely, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC  , OTHER, SensorMessage, gyrx, accelz, 0),
    PB_FIELD( 12, FLOAT   , REQUIRED, STATIC  , OTHER, SensorMessage, gyry, gyrx, 0),
    PB_FIELD( 13, FLOAT   , REQUIRED, STATIC  , OTHER, SensorMessage, gyrz, gyry, 0),
    PB_FIELD( 14, FLOAT   , REQUIRED, STATIC  , OTHER, SensorMessage, temp, gyrz, 0),
    PB_FIELD( 15, FLOAT   , REQUIRED, STATIC  , OTHER, SensorMessage, pres, temp, 0),
    PB_FIELD( 16, FLOAT   , REQUIRED, STATIC  , OTHER, SensorMessage, hum, pres, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
